name: Deploy Innovatech Continuo

on:
  push:
    branches:
      - main # se activa solo cuando se hace push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código en el robot
        uses: actions/checkout@v4

      - name: Configurar las credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Desplegar comandos vía AWS SSM (Sin usar SSH)
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Actualizando contenedores Docker mediante automatizacion" \
            --parameters 'commands=["cd /home/ssm-user/Innovatech-Proyecto", "git pull origin main", "DOCKER_BUILDKIT=0 COMPOSE_DOCKER_CLI_BUILD=0 docker-compose up --build --force-recreate -d"]' \
            --output text